import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Copy,Users,Swords} from 'lucide-react';
import {MonsterData,SavedMonsterEntry,BattleModeType} from '../types';
import {getSavedMonsters} from '../utils/storage';
interface Props{monster:MonsterData;onBack:()=>void;onBattle:(room:string,ws:WebSocket,player:number,monster:MonsterData,mode:BattleModeType,players:MonsterData[])=>void}
type LS={connected:boolean[];ready:boolean[];selected:boolean[];mode:BattleModeType|null;host:number;requiredPlayers:number;teams:number[]};
export const OnlineLobbyScreen:React.FC<Props>=({monster,onBack,onBattle})=>{
 const wsRef=useRef<WebSocket|null>(null), handed=useRef(false), selectedRef=useRef(monster), playerRef=useRef(0), roomRef=useRef('');
 const [joinMode,setJoinMode]=useState<'create'|'join'>('create'),[code,setCode]=useState(''),[room,setRoom]=useState(''),[player,setPlayer]=useState(0);
 const [status,setStatus]=useState('ルームを作成するか、コードで参加してください'),[error,setError]=useState('');
 const [lobby,setLobby]=useState<LS>({connected:[false,false,false,false],ready:[false,false,false,false],selected:[false,false,false,false],mode:null,host:0,requiredPlayers:2,teams:[0,1,0,1]});
 const [saved,setSaved]=useState<SavedMonsterEntry[]>([]),[selected,setSelected]=useState<MonsterData>(monster);
 useEffect(()=>setSaved(getSavedMonsters()),[]);
 const cleanup=()=>{const w=wsRef.current;if(w&&w.readyState<WebSocket.CLOSING)w.close();wsRef.current=null};
 const send=(o:any)=>{const w=wsRef.current;if(w?.readyState===WebSocket.OPEN){w.send(JSON.stringify(o));return true}setError('サーバーとの接続が切れています');return false};
 const networkMonster=(m:MonsterData)=>m;
 const connect=(action:'create'|'join')=>{cleanup();setError('');handed.current=false;const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${proto}://${location.host}/ws`);wsRef.current=ws;
  ws.onopen=()=>ws.send(JSON.stringify(action==='create'?{type:'create'}:{type:'join',room:code.trim().toUpperCase()}));
  ws.onmessage=e=>{let m:any;try{m=JSON.parse(e.data)}catch{return};if(m.type==='room_created'||m.type==='joined'){roomRef.current=m.room;playerRef.current=m.player;setRoom(m.room);setPlayer(m.player);setStatus(m.type==='room_created'?'ルーム作成完了。参加者を待っています…':`P${m.player+1}として参加しました`);ws.send(JSON.stringify({type:'select_monster',monster:networkMonster(selectedRef.current)}));return}if(m.type==='lobby_state'){setLobby(m.state);return}if(m.type==='monster_selected'){setStatus('モンスター選択をサーバーに登録しました');return}if(m.type==='ready_ack'){setStatus('READY完了！ 他のプレイヤーを待っています…');return}if(m.type==='waiting'){setStatus(m.message||'待機中…');return}if(m.type==='battle_start'){handed.current=true;onBattle(m.room||roomRef.current,ws,m.player??playerRef.current,selectedRef.current,m.mode,m.players||[]);return}if(m.type==='error')setError(m.message||'通信エラー')};
  ws.onerror=()=>setError('サーバーに接続できません');ws.onclose=()=>{if(!handed.current)setStatus('接続が終了しました')};};
 useEffect(()=>()=>{if(!handed.current)cleanup()},[]);
 const choose=(m:MonsterData)=>{selectedRef.current=m;setSelected(m);setError('');send({type:'select_monster',monster:networkMonster(m)})};
 const setMode=(mode:BattleModeType)=>send({type:'set_mode',mode});
 const setTeam=(team:number)=>{setError('');send({type:'set_team',team})};
 const required=lobby.requiredPlayers||((lobby.mode==='1vs1')?2:4);const enough=lobby.connected.slice(0,required).every(Boolean);const canReady=!!room&&!!selected&&!lobby.ready[player];
 const labels:{mode:BattleModeType;label:string}[]=[{mode:'1vs1',label:'⚔ 1 vs 1'},{mode:'2vs2',label:'🤝 2 vs 2'},{mode:'1vs1vs1vs1',label:'🔥 1 vs 1 vs 1 vs 1'}];
 return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-5"><div className="w-full max-w-4xl bg-slate-900 border border-slate-700 rounded-3xl p-6">
 <button onClick={()=>{cleanup();onBack()}} className="text-slate-400 flex gap-2 mb-5"><ArrowLeft/>戻る</button><div className="flex gap-3 items-center"><Swords/><h1 className="text-2xl font-black">オンラインルーム <span className="text-xs text-cyan-300">v2.8.2.1</span></h1></div><p className="text-sm text-slate-400 mb-5">ルーム → ホストがモード選択 → 必要人数参加 → 各自モンスター選択 → READY</p>
 {!room&&<><div className="grid grid-cols-2 gap-2 mb-3"><button onClick={()=>setJoinMode('create')} className="p-3 bg-amber-500 text-black rounded-xl font-bold">ルームを作る</button><button onClick={()=>setJoinMode('join')} className="p-3 bg-cyan-600 rounded-xl font-bold">コードで参加</button></div>{joinMode==='join'&&<input value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6))} className="w-full p-4 bg-slate-950 rounded-xl text-center text-2xl mb-2" placeholder="6桁コード"/>}<button disabled={joinMode==='join'&&code.length!==6} onClick={()=>connect(joinMode)} className="w-full p-4 bg-emerald-500 text-black rounded-xl font-black disabled:opacity-40">{joinMode==='create'?'作成':'参加'}</button></>}
 {room&&<><div className="text-center my-4"><div className="text-4xl font-black text-amber-300 tracking-[.2em]">{room}</div><button onClick={()=>navigator.clipboard.writeText(room)} className="mt-2 p-2 bg-slate-800 rounded"><Copy className="inline"/> コピー</button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mb-4">{[0,1,2,3].map(i=><div key={i} className={`p-3 rounded-xl border ${lobby.connected[i]?'border-emerald-500':'border-slate-700 opacity-60'}`}><Users className="inline"/> P{i+1}<div className="text-xs">{lobby.connected[i]?(lobby.ready[i]?'READY ✓':'接続済み'):'空き'}</div>{lobby.mode==='2vs2'&&<div className={`text-xs font-black mt-1 ${(lobby.teams?.[i]??(i%2))===0?'text-cyan-300':'text-rose-300'}`}>Team {(lobby.teams?.[i]??(i%2))===0?'A':'B'}</div>}</div>)}</div>
 {player===0?<div className="grid md:grid-cols-3 gap-2 mb-4">{labels.map(x=><button key={x.mode} onClick={()=>setMode(x.mode)} className={`p-4 rounded-xl border font-black ${lobby.mode===x.mode?'bg-indigo-600 border-indigo-300':'bg-slate-800 border-slate-700'}`}>{x.label}</button>)}</div>:<div className="p-3 bg-slate-800 rounded-xl text-center mb-4">選択モード：{lobby.mode||'ホストの選択待ち'}</div>}
 {lobby.mode&&<><div className="text-sm text-center mb-3">必要人数：{required}人　現在：{lobby.connected.filter(Boolean).length}人 {!enough&&'（参加者待ち）'}</div>{lobby.mode==='2vs2'&&<div className="mb-4 p-3 rounded-2xl bg-slate-950 border border-slate-700"><div className="text-sm font-black text-center mb-2">🤝 自分のチームを選択</div><div className="grid grid-cols-2 gap-2"><button disabled={lobby.ready[player]} onClick={()=>setTeam(0)} className={`p-3 rounded-xl font-black border ${(lobby.teams?.[player]??0)===0?'bg-cyan-600 border-cyan-300':'bg-slate-800 border-slate-700'}`}>🔵 Team A</button><button disabled={lobby.ready[player]} onClick={()=>setTeam(1)} className={`p-3 rounded-xl font-black border ${(lobby.teams?.[player]??0)===1?'bg-rose-600 border-rose-300':'bg-slate-800 border-slate-700'}`}>🔴 Team B</button></div><div className="text-[11px] text-slate-400 text-center mt-2">A/Bそれぞれ2人になるように選択。READY後は変更できません。</div></div>}<div className="font-black mb-2">自分のモンスター</div><div className="grid sm:grid-cols-2 gap-2 max-h-56 overflow-y-auto">{[{id:monster.id,name:monster.name,monster,wins:0,battles:0,savedAt:0} as SavedMonsterEntry,...saved.filter(x=>x.monster.id!==monster.id)].map(e=><button key={e.monster.id} onClick={()=>choose(e.monster)} className={`p-3 rounded-xl border flex gap-3 text-left ${selected.id===e.monster.id?'border-cyan-400 bg-cyan-950/40':'border-slate-700'}`}><img src={e.monster.imageSrc} className="w-14 h-14 object-contain"/><div><b>{e.monster.name}</b><div className="text-xs">{e.monster.type} / HP {e.monster.stats.maxHp}</div></div></button>)}</div><button disabled={!canReady} onClick={()=>{setError('');setStatus('READYを送信中…');send({type:'ready',monster:networkMonster(selectedRef.current)})}} className="w-full mt-4 p-4 bg-emerald-500 text-black rounded-xl font-black disabled:opacity-40">{lobby.ready[player]?'✓ READY':'このモンスターでREADY'}</button></>}
 <div className="text-center text-sm text-slate-400 mt-3">{status}</div></>}{error&&<div className="mt-3 p-3 bg-rose-950 border border-rose-500 rounded">{error}</div>}</div></div>;
};